tasks:
  - name: utils
    before: |
      sudo apt-get update
      sudo apt-get install -y tree jq
  - name: Install PowerShell
    before: |
      sudo apt-get update
      sudo apt-get install -y wget apt-transport-https software-properties-common
      source /etc/os-release
      wget -q https://packages.microsoft.com/config/ubuntu/$VERSION_ID/packages-microsoft-prod.deb
      sudo dpkg -i packages-microsoft-prod.deb
      rm packages-microsoft-prod.deb
      sudo apt-get update
      sudo apt-get install -y powershell
  - name: Install AWS CLI
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      # Install required dependencies
      sudo apt-get update
      sudo apt-get install -y unzip

      # Navigate to the appropriate directory
      cd /workspace

      # Download and install AWS CLI
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install

      # Verify installation
      aws --version

      # Optional: Navigate to your workspace directory
      cd $THETA_WORKSPACE_ROOT/AWS_Example_

  - name: Setup
    command: |
      # Run any additional setup commands here
      echo "AWS CLI installed and ready to use."  
  - init: |
      echo "export AWS_CLI_AUTO_PROMPT=on-partial" >> ~/.bashrc
      source ~/.bashrc
  - name: pythonboto3
    before: |
      pip3 install boto3


