tasks:
  - name: utils 
    before: |
      sudo apt-get install tree
      sudo apt-get install jq
  - name: aws-cli
    env:
        export AWS_CLI_AUTO_PROMT: on-partial
    before: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THETA_WORKSPACE_ROOT/AWS_Example_      
  - init: |
      echo "export AWS_CLI_AUTO_PROMPT=on-partial" >> ~/.bashrc
      source ~/.bashrc
  - name: Initialize
    command: |
      source ./latest-one-bucket
      bucket=$(./latest-one-bucket)
      echo "MY_bucket is: $bucket"

