#!/usr/bin/env bash

cd /workspace 
curl -L "https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-arm64.zip" -o "smacli.zip"
mv smacli.zip samcli.zip
unzip samcli.zip -d sam-installation
sudo ./sam-installation/install
cd /workspaces/AWS_Example_/
sam --version
rm /workspaces/AWS_Example_/samcli.zip