#!/usr/bin/env bash
echo "=listing buckets which is latest one created "
aws s3api list-buckets --query 'Buckets[*].{Name: Name, CreationDate: CreationDate}' | jq -r 'sort_by(.CreationDate) | reverse | .[0] |.Name'