#!/bin/bash

while true; do

        # Read user choice
        read -p "Enter your choice (1-9): " choice

        echo "Select an option:"
        echo "1. Find users exist and there groups"
        echo "2. Find group and its users"
        echo "3. Create a IAM user "
        echo "4. Create a New access key for NEW IAM user "
        echo "5. delete access key and disable old access key "
        echo "6. Find group policy"
        echo "7. User and group and add user to group"
        echo "8. group and policy and add policy to group"
        echo "9. exit"

        case $choice in
        1)
        # List all users
        USERS=$(aws iam list-users --query "Users[].UserName" --output text)
        echo "List of users $USERS "

        # Loop through each user and find their groups
        for USER in $USERS; do
            echo "Checking groups for user: $USER"

            read "Enter the name "
            # List the groups for each user
            GROUPS=$(aws iam list-groups-for-user --user-name "$USER" --query "Groups[].GroupName" --output text)

            if [ -n "$GROUPS" ]; then
                echo "User '$USER' is part of the following groups: $GROUPS"
            else
                echo "User '$USER' is not part of any groups."
            fi
        done
        ;;

        2)
        # Check if the group exists
        read -p "Enter the name of the Group: " GROUP_NAME
        # Check if the user has entered a value
        if [ -z "$GROUP_NAME" ]; then
            echo "User name cannot be empty. Please try again."
            continue
        fi

        GROUP_EXISTS=$(aws iam list-groups --query "Groups[?GroupName=='$GROUP_NAME'].GroupName" --output text)

        if [ "$GROUP_NAME" == "$GROUP_EXISTS" ]; then
            echo "Group '$GROUP_NAME' exists."
            echo "Listing users in group '$GROUP_NAME'..."

            # List users in the group
            aws iam get-group --group-name "$GROUP_NAME" --query "Users[].UserName" --output text
        else
            echo "Group '$GROUP_NAME' does not exist."
        fi
        ;;

        3)
        # 3. Create an IAM user
        read -p "Enter the name of the User: " USER_NAME
        # Check if the user has entered a value
        if [ -z "$USER_NAME" ]; then
            echo "User name cannot be empty. Please try again."
            continue
        fi

        # Create the IAM user
        aws iam create-user --user-name "$USER_NAME"
        # Check if the user creation was successful
        if [ $? -eq 0 ]; then
            echo "IAM user '$USER_NAME' created successfully."
        else
            echo "Failed to create IAM user '$USER_NAME'."
        fi
        ;;


        4)
        # Prompt user for the IAM username
        read -p "Enter the name of the IAM User: " USER_NAME

        # Check if the user entered a name
        if [ -z "$USER_NAME" ]; then
            echo "Error: IAM User name cannot be empty."
            continue
        fi

        # List access keys for the IAM user
        ACCESS_KEYS=$(aws iam list-access-keys --user-name "$USER_NAME" --query 'AccessKeyMetadata' --output text)

        # Check if the user has existing access keys
        if [ -z "$ACCESS_KEYS" ]; then
            echo "No access keys found for user $USER_NAME. Creating a new access key..."
            NEW_ACCESS_KEY=$(aws iam create-access-key --user-name "$USER_NAME")

            # Check if the access key was successfully created ]]]] $? -eq 0  error codes the previous command was 
            if [ $? -eq 0 ]; then
                echo "New access key created successfully for user $USER_NAME:"
                echo "$NEW_ACCESS_KEY"
            else
                echo "Error: Failed to create a new access key for user $USER_NAME."
            fi
        else
            echo "Access keys found for user $USER_NAME. Please delete the existing keys before creating a new one."
        fi
        ;;

        5)
        # "delete access key and disable old access key "
        # Prompt user for the IAM username
        read -p "Enter the name of the IAM User: " USER_NAME

        # Check if the user entered a name
        if [ -z "$USER_NAME" ]; then
            echo "Error: IAM User name cannot be empty."
            continue
        fi

        # Assuming USER_NAME is already set
        ACCESS_KEYS=$(aws iam list-access-keys --user-name "$USER_NAME" --query 'AccessKeyMetadata[*].AccessKeyId' --output text)

        if [ -z "$ACCESS_KEYS" ]; then
        echo "No access keys found for user: $USER_NAME"
        continue
        fi

        echo "Access keys for $USER_NAME: $ACCESS_KEYS"

        for ACCESS_KEY_ID in $ACCESS_KEYS; do
        echo "Deleting access key: $ACCESS_KEY_ID for user: $USER_NAME"
        aws iam delete-access-key --user-name "$USER_NAME" --access-key-id "$ACCESS_KEY_ID"

        if [ $? -eq 0 ]; then
            echo "Successfully deleted access key: $ACCESS_KEY_ID"
        else
            echo "Failed to delete access key: $ACCESS_KEY_ID"
        fi
        done
        ;;


        6)
        # "4. Find groups policys"
        read -p "Enter the name of the Group: " GROUP_NAME
        # Check if the user has entered a value
        if [ -z "$GROUP_NAME" ]; then
            echo "User name cannot be empty. Please try again."
            continue
        fi
        
        if ! aws iam list-group-policies --group-name "$GROUP_NAME" > /dev/null 2>&1; then
            echo "Error: Unable to retrieve policies. Please check if the group exists and you have sufficient permissions."
            continue
        fi
        aws iam list-group-policies \
         --group-name $GROUP_NAME \
         --output table
        ;;

        7)
        #  "5. User and group and add user to group"
        read -p "Enter the name of the Group: " GROUP_NAME
        if [ -z "$GROUP_NAME" ]; then
            echo "Group name cannot be empty. Please try again."
            continue
        fi

        read -p "Enter the name of the IAM User: " USER_NAME
        if [ -z "$USER_NAME" ]; then
            echo "Error: IAM User name cannot be empty."
            continue
        fi

        # Check if the group and user exist
        if ! aws iam list-group --group-name "$GROUP_NAME" > /dev/null 2>&1 || ! aws iam get-user --user-name "$USER_NAME" > /dev/null 2>&1; then
            echo "Error: Unable to retrieve Group or User. Please check if the group and user exist and you have sufficient permissions."
            continue
        fi

        # Add the user to the group
        if aws iam add-user-to-group --user-name "$USER_NAME" --group-name "$GROUP_NAME"; then
            echo "User '$USER_NAME' successfully added to the group '$GROUP_NAME'."
        else
            echo "Error: Failed to add user '$USER_NAME' to the group '$GROUP_NAME'. Please check your permissions and try again."
            exit 1
        fi
        ;;

        8)
            #  "6. group and policy and add policy to group"

        read -p "Enter the name of the Group: " GROUP_NAME
        if [ -z "$GROUP_NAME" ]; then
            echo "Group name cannot be empty. Please try again."
            continue
        fi

        read -p "Enter the name of the policy: " POLICY_NAME
        if [ -z "$POLICY_NAME" ]; then
            echo "Error: policy name cannot be empty."
            continue
        fi
        

        # Check if the group and user exist
        if ! aws iam list-group --group-name "$GROUP_NAME" > /dev/null 2>&1 || ! aws iam get-policy --policy-arn "$POLICY_NAME" > /dev/null 2>&1; then
            echo "Error: Unable to retrieve Group or Policy. Please check if the group and Policy exist and you have sufficient permissions."
            exit 1
        fi
        ;;

        9)
           # Exit
        echo "Exiting..."
        break
        ;;

        *)
        echo "Invalid choice, please try again."
        ;;


    esac
done















# USERNAME=$1
# POLICY_NAME="IAMFullAccessPolicy"
# POLICY_EXISTS=$(aws iam list-policies --query "Policies[?PolicyName=='$POLICY_NAME'].PolicyName" --output text)
# if [ "$POLICY_NAME" == "$POLICY_EXISTS" ]; then 

#     echo "Policy '$POLICY_NAME' exists."

# else 
#     # Create a custom policy that allows full access to IAM
#     aws iam create-policy --policy-name $POLICY_NAME --policy-document '{
#        "Version": "2012-10-17",
#         "Statement": [
#         {
#             "Effect": "Allow",
#             "Action": "iam:*",
#             "Resource": "*"
#         }       
#                      ]
#        }'
# fi

# # Attach the custom policy to the user
# POLICY_ARN=$(aws iam list-policies --query "Policies[?PolicyName=='IAMFullAccessPolicy'].Arn" --output text)
# echo   "policy Arn  $POLICY_ARN"
# aws iam attach-user-policy --user-name $USERNAME --policy-arn $POLICY_ARN
# # Output confirmation with user and policys attached to it 
# aws iam list-attached-user-policies --user-name $USERNAME
