AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: "String"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/job-function/ViewOnlyAccess
