AWSTemplateFormatVersion: 2010-09-09
Description: A CloudFormation template to run an EC2 instance 

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
  SubnetID: 
    Type: String
    Default: subnet-03f75fbc3183b081b
  ImageID:
    Type: String  
    Default: ami-09c0d3755326acbf0
  myVPC:
    Type: String
    Default: vpc-08211df302dec65c5

Resources:
  MyEC2Instance: 
    Type: AWS::EC2::Instance
    Properties: 
      InstanceType: !Ref InstanceType
      ImageId: !Ref ImageID
      SubnetId: !Ref SubnetID
      IamInstanceProfile: !Ref EC2InstanceProfile
      SecurityGroupIds:
        - !GetAtt InstanceSecurityGroup.GroupId
      UserData: !Base64 |
        #!/bin/bash
        yum update -y             # Update the package repository
        yum install -y httpd      # Intall Apache
        systemctl enable httpd    # Enable Apache to start on boot
        systemctl start httpd     # Start the Apache service
        echo "Hello from Apache" > /var/www/html/index.html  # Create a simple index page

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP to client host
      VpcId: !Ref myVPC
      SecurityGroupIngress:
        - IpProtocol: -1  # Allow all inbound traffic
          FromPort: -1    # No specific port (applies to all protocols)
          ToPort: -1      # No specific port (applies to all protocols)
          CidrIp: 0.0.0.0/0  # Allow from any IP address
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
  # Create the IAM Role for the EC2 Instance
  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: "sts:AssumeRole"
            Principal:
              Service: ec2.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2Role

    