#!/usr/bin/env bash

# Create a vpc 

VPC_id=(aws ec2 create-vpc --cidr-block "172.28.0.0/24" \
    --tag-specifications 'ResourceType=vpc,Tags=[{Key=Name,Value=vpc-basic-Ec2-2}]' \
    --region ap-south-1 \
    --query "Vpc.VpcId" \
    --output text)


# Create a IGW 

# attach a IGW

# Create a new-subnet

# explicty associate subnet

# add a route for our RT to out IGW 
