AWSTemplateFormatVersion: "2010-09-09"
Description: "This example template shows how to create an Amazon SQS queue."
Parameters: 
  AlarmEmail: 
    Default: "jane.doe@example.com"
    Description: "Email address to notify of operational issues"
    Type: "String"
Resources: 
  MyQueue: 
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: "SampleQueue"
  AlarmTopic: 
    Type: AWS::SNS::Topic
    Properties: 
      Subscription: 
        - Endpoint: 
            Ref: "AlarmEmail"
          Protocol: "email"